<?php

//English version

return [
    'title' => 'Report',
    'republic' => 'Republic of Rwanda',
    'ministry' => 'Ministry of Justice',
    'report_title' => 'Dispute Resolution Report Number: ',
    'issue_title' => 'Dispute Title:',
    'raiser' => 'Complainant:',
    'accused' => 'Accused:',
    'location' => 'Location:',
    'meeting_datetime' => 'Meeting Date & Time:',
    'raiser_wish' => 'Complainant’s Request:',
    'accused_wish' => 'Accused’s Request:',
    'abunzi' => 'Abunzi Committee',
    'witnesses' => 'Witnesses:',
    'attendees' => 'Meeting Attendees:',
    'final_resolution' => 'Final Resolution:',
    'report_date' => 'Report Prepared On:',
    'prepared_by' => 'Justice Committee Members:',
    'preparer' => 'Report Preparer',
    'committee_lead' => 'Committee Lead',
    'disclaimer' => 'This report is an official record of the mediation session.',
    'software_notice' => 'Report generated by Abunzi Software.',
    'identification' => 'Victim \'sIdentification Card No'
];
